project 'smartbnbkit/smartbnbkit.xcodeproj'

target 'smartbnbkit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON'

end
